#!/bin/bash
if [ -d web-src -a -e web-src ]; then
    echo "已存在 src 目录，跳过创建..."
else
    mkdir web-src
fi

echo ">>> 开始备份"

cp -r ./assets ./public ./.vitepress ./send ./web-src
cp -r ./index.md ./welcome.md \
./acovia-server \
./fovlin-notes \
./fovlin \
./novel \
./web-src

npx vitepress build

rsync -rv ./.vitepress/dist/ acovia.net:/home/fovlin/service/web/

rsync -rv ./web-src acovia.net:/home/fovlin/files/documents/

rsync -rv ./web-src/ acovia.net:/home/fovlin/service/web/